### ISSUE TITLE
Unable to run app as instructed without a couple of extra steps.

### ISSUE THREAD

**Issue by stuartwilliamchaulk** [joeeames/lightning-voter-demo#1]
Hi.  Tried running as instructred, but unless I missed something, a few steps were missing that were required to get it up and running: specifically, running `typings install` and `npm run tsc`.  Note I was doing this in the context of the PS course.

[edit] nm, was treating this as the compiled version.

**Comment by joeeames** [comment]
things are ok then?

**Comment by stuartwilliamchaulk** [comment]
Yep. Issue was that my proxy was blocking github, so I had to download.
Downloaded the master instead of the "starting-point" branch.  Switched
over and all good. Thanks for getting back to me.
