### ISSUE TITLE
Any resource I can follow to convert my app?

### ISSUE THREAD

**Issue by divyanshu-rawat** [joeeames/lightning-voter-demo#2]
Any phase 2 will release in a month or two.
But I have an urgent requirement for migration from ng-1 to ng-2.
So, can you suggest me any resource that I can follow to convert my app to ng-2?
will this work [Resource](https://angular.io/docs/ts/latest/guide/upgrade.html)

**Comment by joeeames** [comment]
I disagree with some of the official docs, plus it covers very little. Otherwise, there's no resource that I know of. You can try following this repo here: https://github.com/joeeames/ngVikingsMigrationWorkshop
